#!/usr/bin/env node
/*
 * build.js — concatène les sources de src/ en un seul dork-generator.html
 * autonome (aucune dépendance, ouvrable par double-clic).
 *
 * Usage : node build.js
 *
 * Dev : éditer les fichiers dans src/ puis relancer `node build.js`.
 *   - src/head.html  : <!DOCTYPE> .. <head> (meta, title)
 *   - src/style.css  : tout le CSS
 *   - src/body.html  : le markup entre <body> et <script>
 *   - src/js/*.js    : le corps de l'IIFE, découpé par responsabilité
 *
 * Tout le JS tourne dans UNE seule IIFE (scope partagé, pas de modules ES —
 * volontaire pour garder le double-clic file:// sans build ni CORS).
 * L'ordre de concaténation compte : `app` (init DOM) DOIT être en dernier.
 */
const fs = require('fs');
const path = require('path');

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

const head = read('src/head.html').replace(/\s+$/, '');
const css  = read('src/style.css').replace(/\s+$/, '');
const body = read('src/body.html').replace(/\s+$/, '');

const JS_ORDER = [
  'helpers', 'links', 'geo', 'render', 'zip',
  'gen-identite', 'gen-pseudo', 'gen-domaine', 'gen-societe', 'gen-image', 'gen-custom',
  'app', // app DOIT rester en dernier : init DOM (listeners, restoreFields, thème)
];
const js = JS_ORDER
  .map((name) => read('src/js/' + name + '.js').replace(/\s+$/, ''))
  .join('\n\n');

const banner = '<!-- GENERATED by build.js — DO NOT EDIT. Edit src/ then run `node build.js`. -->\n';

const html =
  banner +
  head + '\n' +
  '<style>\n' + css + '\n</style>\n' +
  '</head>\n' +
  '<body>\n\n' +
  body + '\n\n' +
  '<script>\n' +
  '(function() {\n' +
  "  'use strict';\n\n" +
  js + '\n\n' +
  '})();\n' +
  '</script>\n\n' +
  '</body>\n' +
  '</html>\n';

fs.writeFileSync(path.join(root, 'dork-generator.html'), html);
console.log('built dork-generator.html (' + html.split('\n').length + ' lines)');
